name: build

on:
  push:
    branches:
    - main
    - release**
    paths-ignore:
      - '**.md'
      - '**.rst'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'

# This will cancel previous run if a newer job that obsoletes the said previous
# run, is started.
# Based on https://github.com/zulip/zulip/commit/4a11642cee3c8aec976d305d51a86e60e5d70522
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.run_id }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}-latest
    # We need an explicit timeout because sometimes the batch_runner test never
    # completes.
    timeout-minutes: 6
    strategy:
      fail-fast: False
      matrix:
        os: [windows, ubuntu, macos]
        python-version: ["3.10"]
        include:
          - os: ubuntu
            python-version: "3.9"
          - os: ubuntu
            python-version: "3.8"
          - os: ubuntu
            python-version: "3.7"
          # Disabled for now. See https://github.com/projectmesa/mesa/issues/1253
          #- os: ubuntu
          #  python-version: 'pypy-3.8'

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('Pipfile.lock') }}
    - name: Install dependencies
      run: pip install wheel && pip install .[dev]
    - name: Test with pytest
      run: pytest --cov=mesa tests/ --cov-report=xml
    - if: matrix.os == 'ubuntu'
      name: Codecov
      uses: codecov/codecov-action@v2

  lint-flake:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - run: pip install flake8
    - name: Lint with flake8
      # Use settings from mesas .flake8 file
      run: flake8 . --count --show-source --statistics

  lint-black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - run: pip install black[jupyter]
    - name: Lint with black
      run: black --check --exclude=mesa/cookiecutter-mesa/* .
