name: Release
on:
  release:
    types:
      - published

jobs:
  release:
    name: Deploy release to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -U pip wheel setuptools
      - name: Build package
        run: python setup.py sdist bdist_wheel
      - name: Upload package as artifact to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: dist/
      - name: Upload packages to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
